"""Write the flat manifest the kernel reads instead of ``modelDescription.xml``.

Format is deliberately trivial -- ``key=value``, one per line, ``#`` comments --
because the consumer is a real-time process with no dependencies. See
``kernel/src/plant/fmu_me.rs::PlantManifest``.
"""

from __future__ import annotations

import json
import platform
from pathlib import Path

from .model_description import ModelDescription, ModelDescriptionError
from .paths import GENERATED_SCHEMA

MANIFEST_NAME = "bobdil_plant.manifest"

#: The three driver inputs. An FMU missing any of them is not a DIL plant.
REQUIRED_INPUTS = (
    "steeringAngleCommand",
    "acceleratorPedalCommand",
    "brakePedalCommand",
)

#: The one output without which there is nothing for the driver to feel.
REQUIRED_OUTPUTS = ("handwheelTorque",)


def _platform_binary_dir() -> str:
    machine = platform.machine().lower()
    system = platform.system().lower()
    if system == "linux":
        return "linux64" if machine in {"x86_64", "amd64"} else "linux32"
    if system == "windows":
        return "win64" if machine in {"amd64", "x86_64"} else "win32"
    if system == "darwin":
        return "darwin64"
    return f"{system}64"


def find_binary(fmu_dir: Path, model_identifier: str) -> Path:
    """Locate the platform binary inside an unpacked FMU.

    An FMU contains compiled native code, which is exactly why "hermetic
    regardless of architecture" is not deliverable (architecture.md 5.4): an FMU
    built on Windows x86_64 will not load on macOS ARM. The error here says so
    plainly rather than failing later inside dlopen.
    """
    binaries = fmu_dir / "binaries"
    wanted = _platform_binary_dir()
    for suffix in (".so", ".dll", ".dylib"):
        candidate = binaries / wanted / f"{model_identifier}{suffix}"
        if candidate.exists():
            return candidate

    present = sorted(p.name for p in binaries.iterdir()) if binaries.exists() else []
    raise ModelDescriptionError(
        f"this FMU has no binary for {wanted}; it ships {present or 'nothing'}.\n"
        "An FMU contains compiled native code, so it must be built on (or for) the "
        "platform it will run on. Rebuild the vehicle on this machine, or use a "
        "prebuilt FMU for this platform."
    )


def schema_fmi_signals() -> dict[str, str]:
    """FMI variable name -> schema field, straight from the generated manifest."""
    signals_path = GENERATED_SCHEMA / "signals.json"
    payload = json.loads(signals_path.read_text(encoding="utf-8"))
    combined: dict[str, str] = {}
    for frame in payload["frames"].values():
        combined.update(frame.get("fmi_signals", {}))
    return combined


def schema_tunables() -> list[dict]:
    signals_path = GENERATED_SCHEMA / "signals.json"
    return json.loads(signals_path.read_text(encoding="utf-8"))["tunables"]


def render(
    description: ModelDescription,
    fmu_dir: Path,
    *,
    vehicle_hash: int = 0,
) -> str:
    missing_inputs = description.require(REQUIRED_INPUTS)
    if missing_inputs:
        raise ModelDescriptionError(
            f"{description.model_name} does not expose the driver inputs "
            f"{missing_inputs}. BobDil drives the VehicleFMI boundary: "
            "steeringAngleCommand, acceleratorPedalCommand, brakePedalCommand."
        )
    missing_outputs = description.require(REQUIRED_OUTPUTS)
    if missing_outputs:
        raise ModelDescriptionError(
            f"{description.model_name} does not expose {missing_outputs}. "
            "Without a handwheel torque there is nothing for the driver to feel, "
            "and the rig has no reason to exist."
        )

    binary = find_binary(fmu_dir, description.model_identifier)
    lines = [
        "# @generated by session/bobdil/manifest.py -- read by kernel/src/plant/fmu_me.rs",
        f"# source: {description.model_name}",
        f"model_identifier={description.model_identifier}",
        f"guid={description.guid}",
        f"library={binary.relative_to(fmu_dir).as_posix()}",
        # Relative, like `library` above. An absolute URI baked in here is
        # correct only on the machine that compiled the FMU: a cache entry
        # built in the container recorded `file:///workspace/...`, which does
        # not exist on the host. The kernel resolves this against the plant
        # directory it was handed and builds the URI at load time.
        "resources=resources",
        f"states={description.continuous_states}",
        f"event_indicators={description.event_indicators}",
        f"vehicle_hash={vehicle_hash:#018x}",
        "",
        "# driver inputs and plant outputs, resolved from modelDescription.xml",
    ]

    wanted = set(REQUIRED_INPUTS) | set(schema_fmi_signals())
    for name in sorted(wanted):
        reference = description.reference(name)
        if reference is not None:
            lines.append(f"vref:{name}={reference}")
        elif name not in REQUIRED_INPUTS:
            # Not fatal: a model that does not publish a signal leaves that
            # field at zero and the UI shows it as unavailable.
            lines.append(f"# absent from this FMU: {name}")

    lines.append("")
    lines.append("# live tunables (FMI variability='tunable')")
    for spec in schema_tunables():
        variable = description.variables.get(spec["fmi"])
        if variable is None:
            lines.append(f"# absent: {spec['name']} ({spec['fmi']})")
        elif not variable.is_tunable:
            # The signal exists but was compiled as a constant. This is the
            # BobLib change architecture.md 1.9 calls for: those record fields
            # must not be Evaluate=true if the driver is to change them without
            # a 15-minute recompile.
            lines.append(
                f"# not tunable: {spec['name']} ({spec['fmi']}) is "
                f"variability='{variable.variability}'. It needs to be exported as "
                "an FMI parameter with variability='tunable' to be changed live."
            )
        else:
            lines.append(f"tunable:{spec['id']}={variable.value_reference}")

    return "\n".join(lines) + "\n"


def write(description: ModelDescription, fmu_dir: Path, *, vehicle_hash: int = 0) -> Path:
    path = fmu_dir / MANIFEST_NAME
    path.write_text(render(description, fmu_dir, vehicle_hash=vehicle_hash), encoding="utf-8")
    return path
