"""Emit include/bobdil_frames.h -- the C view, for any native consumer."""

from __future__ import annotations

from .schema import Schema

HEADER = """/* @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT. */
#ifndef BOBDIL_FRAMES_H
#define BOBDIL_FRAMES_H

#include <stdint.h>

#define BOBDIL_LAYOUT_HASH     {layout_hash:#018x}ULL
#define BOBDIL_LAYOUT_REVISION {layout_revision}
#define BOBDIL_SCHEMA_VERSION  {schema_version}
"""


def render(schema: Schema) -> str:
    out = [
        HEADER.format(
            layout_hash=schema.layout_hash,
            layout_revision=schema.layout_revision,
            schema_version=schema.schema_version,
        )
    ]
    for frame in schema.frames:
        out.append(f"/* {frame.doc} */")
        out.append("typedef struct {")
        for field in frame.fields:
            comment = f" /* [{field.unit}] {field.doc} */".rstrip()
            out.append(f"    {schema.c_type(field)} {field.name};{comment}")
        out.append(f"}} bobdil_{frame.name}_t;")
        out.append(f"#define BOBDIL_{frame.name.upper()}_SIZE {frame.size_bytes}")
        out.append(f'#define BOBDIL_{frame.name.upper()}_SHM "{frame.shm_name}"')
        out.append("")
    for enum in schema.enums:
        out.append(f"/* {enum.doc} */")
        for key, value in enum.values.items():
            out.append(f"#define BOBDIL_{enum.name.upper()}_{key.upper()} {value}ULL")
        out.append("")
    out.append("#endif /* BOBDIL_FRAMES_H */")
    return "\n".join(out)
