"""Emit session/bobdil/generated/frames.py -- the session's view of the schema.

The session is off the real-time path, so it reads frames with `struct`, which
is fast enough and keeps the module dependency-free.
"""

from __future__ import annotations

from .schema import Schema

HEADER = '''"""@generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT.

Regenerate with `make codegen`.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import ClassVar

LAYOUT_HASH = {layout_hash:#018x}
LAYOUT_REVISION = {layout_revision}
SCHEMA_VERSION = {schema_version}
'''


def render(schema: Schema) -> str:
    out = [
        HEADER.format(
            layout_hash=schema.layout_hash,
            layout_revision=schema.layout_revision,
            schema_version=schema.schema_version,
        )
    ]
    for frame in schema.frames:
        fmt = "<" + "".join(schema.py_code(f) for f in frame.fields)
        names = [f.name for f in frame.fields]
        out.append("@dataclass(slots=True)")
        out.append(f"class {frame.pascal_name}:")
        out.append(f'    """{frame.doc}"""')
        out.append("")
        for field in frame.fields:
            default = "0.0" if field.type == "f64" else "0"
            annotation = "float" if field.type == "f64" else "int"
            out.append(f"    {field.name}: {annotation} = {default}")
        out.append("")
        out.append(f'    STRUCT: ClassVar[str] = "{fmt}"')
        out.append(f"    SIZE: ClassVar[int] = {frame.size_bytes}")
        if frame.shm_name is not None:
            out.append(f'    SHM_NAME: ClassVar[str] = "{frame.shm_name}"')
        out.append(f"    FIELDS: ClassVar[tuple[str, ...]] = {tuple(names)!r}")
        out.append(
            f"    UNITS: ClassVar[tuple[str, ...]] = {tuple(f.unit for f in frame.fields)!r}"
        )
        out.append("")
        out.append("    @classmethod")
        out.append(f"    def unpack(cls, data: bytes) -> {frame.pascal_name}:")
        out.append("        return cls(*struct.unpack_from(cls.STRUCT, data, 0))")
        out.append("")
        out.append("    def pack(self) -> bytes:")
        out.append(
            "        return struct.pack(self.STRUCT, " + ", ".join(f"self.{n}" for n in names) + ")"
        )
        out.append("")
        out.append("    def as_dict(self) -> dict[str, float | int]:")
        out.append("        return {name: getattr(self, name) for name in self.FIELDS}")
        out.append("")
        out.append("")

    for enum in schema.enums:
        out.append(f"class {enum.pascal_name}:")
        out.append(f'    """{enum.doc}"""')
        out.append("")
        for key, value in enum.values.items():
            out.append(f"    {key.upper()} = {value}")
        out.append("")
        out.append("")

    out.append("@dataclass(frozen=True, slots=True)")
    out.append("class TunableSpec:")
    out.append('    """A parameter that can be changed without recompiling the FMU."""')
    out.append("")
    out.append("    id: int")
    out.append("    name: str")
    out.append("    fmi: str")
    out.append("    unit: str")
    out.append("    min: float")
    out.append("    max: float")
    out.append("")
    out.append("")
    out.append("TUNABLES: tuple[TunableSpec, ...] = (")
    for t in schema.tunables:
        out.append(
            f"    TunableSpec({t.id}, {t.name!r}, {t.fmi!r}, {t.unit!r}, {t.min!r}, {t.max!r}),"
        )
    out.append(")")
    out.append("")
    out.append("TUNABLES_BY_NAME = {t.name: t for t in TUNABLES}")
    out.append("")
    return "\n".join(out)
