"""Emit kernel/src/generated/frames.rs -- the kernel's view of the schema."""

from __future__ import annotations

from .schema import Frame, Schema

HEADER = """// @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT.
// Regenerate with `make codegen`.
#![allow(dead_code)]

/// Fingerprint of the wire layout. Written into every shared-memory segment
/// header so a stale reader refuses to attach rather than misreading bytes.
pub const LAYOUT_HASH: u64 = {layout_hash:#018x};
pub const LAYOUT_REVISION: u64 = {layout_revision};
pub const SCHEMA_VERSION: u64 = {schema_version};
"""


def _struct(schema: Schema, frame: Frame) -> str:
    lines: list[str] = []
    doc = frame.doc or frame.name
    lines.append(f"/// {doc}")
    lines.append("#[repr(C)]")
    lines.append("#[derive(Clone, Copy, Debug, Default, PartialEq)]")
    lines.append(f"pub struct {frame.pascal_name} {{")
    for field in frame.fields:
        if field.doc:
            lines.append(f"    /// {field.doc} [{field.unit}]")
        else:
            lines.append(f"    /// [{field.unit}]")
        lines.append(f"    pub {field.name}: {schema.rust_type(field)},")
    lines.append("}")
    lines.append("")

    names = [f'"{f.name}"' for f in frame.fields]
    units = [f'"{f.unit}"' for f in frame.fields]
    count = len(frame.fields)

    lines.append(f"impl {frame.pascal_name} {{")
    lines.append(f"    pub const SIZE: usize = {frame.size_bytes};")
    lines.append(f"    pub const FIELD_COUNT: usize = {count};")
    lines.append(f'    pub const SHM_NAME: &\'static str = "{frame.shm_name}";')
    lines.append(_array("    ", f"pub const FIELD_NAMES: [&'static str; {count}]", names))
    lines.append(_array("    ", f"pub const FIELD_UNITS: [&'static str; {count}]", units))
    lines.append("")
    lines.append("    /// Field by index, widened to f64. Used by telemetry and replay diffing")
    lines.append("    /// so neither has to know the field list.")
    lines.append("    pub fn field(&self, index: usize) -> f64 {")
    lines.append("        match index {")
    for i, field in enumerate(frame.fields):
        cast = "" if field.type == "f64" else " as f64"
        lines.append(f"            {i} => self.{field.name}{cast},")
    lines.append("            _ => f64::NAN,")
    lines.append("        }")
    lines.append("    }")
    lines.append("")
    lines.append("    /// True when every f64 field is finite. The plant-output guard that")
    lines.append("    /// gates force feedback depends on this being exhaustive.")
    lines.append("    pub fn is_finite(&self) -> bool {")
    finite_fields = [f for f in frame.fields if f.type == "f64"]
    if finite_fields:
        expr = "\n            && ".join(f"self.{f.name}.is_finite()" for f in finite_fields)
        lines.append(f"        {expr}")
    else:
        lines.append("        true")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    plant = frame.plant_signals()
    if plant:
        entries = [f'("{f.fmi}", {list(frame.fields).index(f)})' for f in plant]
        const = f"{frame.name.upper()}_FMI_SIGNALS"
        lines.append(
            "/// (FMI variable name, field index) for every field this frame reads from\n"
            "/// or writes to the plant. The FMU loader resolves value references from this."
        )
        lines.append(_array("", f"pub const {const}: [(&str, usize); {len(plant)}]", entries))
        lines.append("")
    return "\n".join(lines)


def _enums(schema: Schema) -> str:
    lines: list[str] = []
    for enum in schema.enums:
        lines.append(f"/// {enum.doc}")
        lines.append(f"pub mod {enum.name} {{")
        for key, value in enum.values.items():
            lines.append(f"    pub const {key.upper()}: u64 = {value};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _tunables(schema: Schema) -> str:
    if not schema.tunables:
        return ""
    lines = [
        "/// Parameters exposed as FMI `tunable`, settable mid-session.",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct TunableSpec {",
        "    pub id: u32,",
        "    pub name: &'static str,",
        "    pub fmi: &'static str,",
        "    pub min: f64,",
        "    pub max: f64,",
        "}",
        "",
        f"pub const TUNABLES: [TunableSpec; {len(schema.tunables)}] = [",
    ]
    for t in schema.tunables:
        lines.append(
            f'    TunableSpec {{ id: {t.id}, name: "{t.name}", fmi: "{t.fmi}", '
            f"min: {t.min!r}, max: {t.max!r} }},"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def _array(indent: str, header: str, items: list[str]) -> str:
    """Render `header = [items];`, wrapped one item per line when it is long.

    Generated Rust is deliberately outside `make fmt-check` -- its shape is this
    emitter's contract, and `make codegen-check` already guards it byte for
    byte, so putting rustfmt's opinion on the same bytes would just give the two
    gates something to disagree about. That leaves readability to the emitter,
    which is what this does: a 33-element unit array is worth reading down a
    column instead of across 300 characters.
    """
    inline = f"{indent}{header} = [{', '.join(items)}];"
    if len(inline) <= 100:
        return inline
    body = "".join(f"{indent}    {item},\n" for item in items)
    return f"{indent}{header} = [\n{body}{indent}];"


def render(schema: Schema) -> str:
    parts = [
        HEADER.format(
            layout_hash=schema.layout_hash,
            layout_revision=schema.layout_revision,
            schema_version=schema.schema_version,
        )
    ]
    parts.extend(_struct(schema, frame) for frame in schema.frames)
    parts.append(_enums(schema))
    parts.append(_tunables(schema))
    return "\n".join(parts)
