"""Emit schema/generated/*.proto -- the control-plane messages.

Protobuf covers session <-> kernel control traffic, which is off the hot path
and where schema evolution matters more than latency. The frame messages here
mirror the packed structs so a control-plane consumer sees the same field set.
"""

from __future__ import annotations

from .schema import Schema

FRAME_HEADER = """// @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT.
syntax = "proto3";

package bobdil;

// Layout fingerprint of the packed structs these messages mirror.
// Emitted as a constant-carrying enum because proto3 has no free constants.
enum Layout {{
  LAYOUT_UNSPECIFIED = 0;
  LAYOUT_REVISION = {layout_revision};
}}
"""

SESSION_PROTO = """// @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT.
syntax = "proto3";

package bobdil;

import "frames.proto";

// Control plane. Session -> kernel over a unix domain socket, off the RT path.

enum KernelId {
  KERNEL_UNSPECIFIED = 0;
  KERNEL_REDUCED14DOF = 1;
  KERNEL_VEHICLE_RT = 2;
  KERNEL_VEHICLE_FMI = 3;
}

message LoadPlant {
  // Directory holding an unpacked FMI 2.0 Model Exchange FMU, or empty for the
  // built-in reduced-order kernel.
  string plant_dir = 1;
  KernelId kernel = 2;
  double step_dt = 3;
  double initial_speed = 4;
}

message SetTunable {
  uint32 tunable_id = 1;
  double value = 2;
}

message StartRecording {
  string path = 1;
}

message ReplayInputs {
  string path = 1;
  bool blind = 2;
}

message Command {
  oneof kind {
    LoadPlant load_plant = 1;
    SetTunable set_tunable = 2;
    StartRecording start_recording = 3;
    ReplayInputs replay_inputs = 4;
    bool reset = 5;
    bool shutdown = 6;
    bool status = 7;
  }
}

message Ack {
  bool ok = 1;
  string detail = 2;
  VehicleState state = 3;
}
"""


def render_frames(schema: Schema) -> str:
    out = [FRAME_HEADER.format(layout_revision=schema.layout_revision)]
    for frame in schema.frames:
        out.append(f"// {frame.doc}")
        out.append(f"message {frame.pascal_name} {{")
        for index, field in enumerate(frame.fields, start=1):
            out.append(f"  {schema.proto_type(field)} {field.name} = {index};")
        out.append("}")
        out.append("")
    return "\n".join(out)


def render_session(schema: Schema) -> str:
    return SESSION_PROTO
