"""Emit view/scripts/generated/frames.gd -- byte offsets for the Godot reader.

Godot never links against the kernel. It maps the state segment read-only and
decodes it with these offsets, which is the whole of its contract with physics
(architecture.md 1.2): the view cannot write, and cannot drift, because both
sides come from this schema.
"""

from __future__ import annotations

from .schema import Schema

HEADER = """# @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT.
# Regenerate with `make codegen`.
class_name BobDilFrames
extends RefCounted

const LAYOUT_HASH: int = {layout_hash}
const LAYOUT_REVISION: int = {layout_revision}
const SCHEMA_VERSION: int = {schema_version}
"""


def render(schema: Schema) -> str:
    # GDScript ints are signed 64-bit, so the layout hash is emitted as the
    # two's-complement value Godot will actually compute when it reads the u64.
    signed_hash = (
        schema.layout_hash - (1 << 64) if schema.layout_hash >= (1 << 63) else schema.layout_hash
    )
    out = [
        HEADER.format(
            layout_hash=signed_hash,
            layout_revision=schema.layout_revision,
            schema_version=schema.schema_version,
        )
    ]
    for frame in schema.frames:
        upper = frame.name.upper()
        out.append(f"# {frame.doc}")
        out.append(f'const {upper}_SHM: String = "{frame.shm_name}"')
        out.append(f"const {upper}_SIZE: int = {frame.size_bytes}")
        out.append(f"const {upper}_OFFSETS: Dictionary = {{")
        for field in frame.fields:
            out.append(f'\t"{field.name}": {field.offset},')
        out.append("}")
        float_fields = [f.name for f in frame.fields if f.type == "f64"]
        # A plain Array literal, not PackedStringArray(...): a GDScript `const`
        # must be a compile-time constant, and a constructor call is not one.
        quoted = ", ".join(f'"{name}"' for name in float_fields)
        out.append(f"const {upper}_FLOAT_FIELDS: Array = [{quoted}]")
        out.append("")

    for enum in schema.enums:
        for key, value in enum.values.items():
            out.append(f"const {enum.name.upper()}_{key.upper()}: int = {value}")
        out.append("")
    return "\n".join(out)
