/* @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT. */
#ifndef BOBDIL_FRAMES_H
#define BOBDIL_FRAMES_H

#include <stdint.h>

#define BOBDIL_LAYOUT_HASH     0x1694a0f5d2961c8bULL
#define BOBDIL_LAYOUT_REVISION 1
#define BOBDIL_SCHEMA_VERSION  1

/* What the driver is asking for, sampled by HidThread and read by StepThread through a seqlock. The three *_command fields are exactly the inputs BobLib.Experiments.Standards.VehicleFMI declares. */
typedef struct {
    uint64_t host_time_ns; /* [ns] CLOCK_MONOTONIC at sample time */
    uint64_t sample_index; /* [-] Monotonic HID sample counter */
    double steering_angle_command; /* [rad] Handwheel angle */
    double accelerator_pedal_command; /* [1]  */
    double brake_pedal_command; /* [1]  */
    double raw_steer_norm; /* [1] Pre-calibration axis value */
    double raw_accel_norm; /* [1]  */
    double raw_brake_norm; /* [1]  */
    uint64_t buttons; /* [-] Button bitmask */
} bobdil_driver_input_t;
#define BOBDIL_DRIVER_INPUT_SIZE 72
#define BOBDIL_DRIVER_INPUT_SHM "bobdil_input"

/* Everything the plant produced this step, plus what the kernel derived from it. This is the frame the view renders, the telemetry recorder writes, and replay compares. The fmi: keys name real VehicleFMI outputs; fields with no fmi: key are computed by the kernel. */
typedef struct {
    double sim_time; /* [s] Plant time */
    uint64_t step_index; /* [-]  */
    uint64_t host_time_ns; /* [ns]  */
    double steering_angle_command; /* [rad]  */
    double accelerator_pedal_command; /* [1]  */
    double brake_pedal_command; /* [1]  */
    double vehicle_speed; /* [m/s]  */
    double acc_x; /* [m/s2]  */
    double acc_y; /* [m/s2]  */
    double handwheel_angle; /* [rad]  */
    double steer_excess; /* [rad]  */
    double handwheel_torque; /* [N.m] Reaction torque; negate for torque applied to the driver */
    double fz_fl; /* [N]  */
    double fz_fr; /* [N]  */
    double fz_rl; /* [N]  */
    double fz_rr; /* [N]  */
    double left_steer_angle; /* [rad]  */
    double right_steer_angle; /* [rad]  */
    double roll; /* [rad]  */
    double sideslip; /* [rad]  */
    double vel_x; /* [m/s]  */
    double vel_y; /* [m/s]  */
    double yaw_vel; /* [rad/s]  */
    double pos_x; /* [m]  */
    double pos_y; /* [m]  */
    double yaw; /* [rad]  */
    double ffb_torque_nm; /* [N.m] Torque after the full conditioning chain */
    double rtf; /* [1] Realtime factor over the last second; 1.0 == realtime */
    double step_time_us; /* [us] Wall-clock cost of this step */
    double step_time_p99_us; /* [us]  */
    uint64_t deadline_misses; /* [-]  */
    uint64_t kernel_id; /* [-] Which PlantKernel produced this frame (see kernel_id enum) */
    uint64_t fault_flags; /* [-] See fault_flags enum */
} bobdil_vehicle_state_t;
#define BOBDIL_VEHICLE_STATE_SIZE 264
#define BOBDIL_VEHICLE_STATE_SHM "bobdil_state"

/* Conditioned force feedback, written by StepThread and consumed by HidThread. HidThread applies its own watchdog on top of this: a stale or non-finite command decays to zero rather than being held. */
typedef struct {
    uint64_t host_time_ns; /* [ns] Stamp used by the HidThread staleness watchdog */
    double torque_nm; /* [N.m]  */
    double spring_coeff; /* [N.m/rad] Optional centering spring for the parked state */
    double damper_coeff; /* [N.m.s/rad]  */
    uint64_t flags; /* [-] See ffb_flags enum */
} bobdil_ffb_command_t;
#define BOBDIL_FFB_COMMAND_SIZE 40
#define BOBDIL_FFB_COMMAND_SHM "bobdil_ffb"

/* Which rung of the plant ladder produced a frame. */
#define BOBDIL_KERNEL_ID_NONE 0ULL
#define BOBDIL_KERNEL_ID_REDUCED14DOF 1ULL
#define BOBDIL_KERNEL_ID_VEHICLE_RT 2ULL
#define BOBDIL_KERNEL_ID_VEHICLE_FMI 3ULL

/* Sticky per-session faults. Any non-zero value is surfaced in the UI. */
#define BOBDIL_FAULT_FLAGS_NONE 0ULL
#define BOBDIL_FAULT_FLAGS_PLANT_NONFINITE 1ULL
#define BOBDIL_FAULT_FLAGS_DEADLINE_MISSED 2ULL
#define BOBDIL_FAULT_FLAGS_FFB_CLAMPED 4ULL
#define BOBDIL_FAULT_FLAGS_TELEMETRY_OVERFLOW 8ULL
#define BOBDIL_FAULT_FLAGS_DEVICE_LOST 16ULL
#define BOBDIL_FAULT_FLAGS_PLANT_STEP_FAILED 32ULL
#define BOBDIL_FAULT_FLAGS_INPUT_STALE 64ULL

/* State of the feedback path. */
#define BOBDIL_FFB_FLAGS_NONE 0ULL
#define BOBDIL_FFB_FLAGS_ACTIVE 1ULL
#define BOBDIL_FFB_FLAGS_RAMPING_DOWN 2ULL
#define BOBDIL_FFB_FLAGS_DISABLED 4ULL
#define BOBDIL_FFB_FLAGS_WATCHDOG_TRIPPED 8ULL

#endif /* BOBDIL_FRAMES_H */