/* @generated by codegen/ from schema/bobdil_signals.yaml -- DO NOT EDIT. */
#ifndef BOBDIL_FRAMES_H
#define BOBDIL_FRAMES_H

#include <stdint.h>

#define BOBDIL_LAYOUT_HASH     0xc39036ce6c8ab845ULL
#define BOBDIL_LAYOUT_REVISION 1
#define BOBDIL_SCHEMA_VERSION  1

/* What the driver is asking for, sampled by HidThread and read by StepThread through a seqlock. The three *_command fields are exactly the inputs BobLib.Experiments.Standards.VehicleFMI declares. */
typedef struct {
    uint64_t host_time_ns; /* [ns] CLOCK_MONOTONIC at sample time */
    uint64_t sample_index; /* [-] Monotonic HID sample counter */
    double steering_angle_command; /* [rad] Handwheel angle */
    double accelerator_pedal_command; /* [1]  */
    double brake_pedal_command; /* [1]  */
    double raw_steer_norm; /* [1] Pre-calibration axis value */
    double raw_accel_norm; /* [1]  */
    double raw_brake_norm; /* [1]  */
    uint64_t buttons; /* [-] Button bitmask */
} bobdil_driver_input_t;
#define BOBDIL_DRIVER_INPUT_SIZE 72
#define BOBDIL_DRIVER_INPUT_SHM "bobdil_input"

/* Everything the plant produced this step, plus what the kernel derived from it. This is the frame the view renders, the telemetry recorder writes, and replay compares. The fmi: keys name real VehicleFMI outputs; fields with no fmi: key are computed by the kernel. */
typedef struct {
    double sim_time; /* [s] Plant time */
    uint64_t step_index; /* [-]  */
    uint64_t host_time_ns; /* [ns]  */
    double steering_angle_command; /* [rad]  */
    double accelerator_pedal_command; /* [1]  */
    double brake_pedal_command; /* [1]  */
    double vehicle_speed; /* [m/s]  */
    double acc_x; /* [m/s2]  */
    double acc_y; /* [m/s2]  */
    double handwheel_angle; /* [rad]  */
    double steer_excess; /* [rad]  */
    double handwheel_torque; /* [N.m] Reaction torque; negate for torque applied to the driver */
    double fz_fl; /* [N]  */
    double fz_fr; /* [N]  */
    double fz_rl; /* [N]  */
    double fz_rr; /* [N]  */
    double left_steer_angle; /* [rad]  */
    double right_steer_angle; /* [rad]  */
    double roll; /* [rad]  */
    double sideslip; /* [rad]  */
    double vel_x; /* [m/s]  */
    double vel_y; /* [m/s]  */
    double yaw_vel; /* [rad/s]  */
    double pos_x; /* [m]  */
    double pos_y; /* [m]  */
    double yaw; /* [rad]  */
    double ffb_torque_nm; /* [N.m] Torque after the full conditioning chain */
    double rtf; /* [1] Realtime factor over the last second; 1.0 == realtime */
    double step_time_us; /* [us] Wall-clock cost of this step */
    double step_time_p99_us; /* [us]  */
    uint64_t deadline_misses; /* [-]  */
    uint64_t kernel_id; /* [-] Which PlantKernel produced this frame (see kernel_id enum) */
    uint64_t fault_flags; /* [-] See fault_flags enum */
} bobdil_vehicle_state_t;
#define BOBDIL_VEHICLE_STATE_SIZE 264
#define BOBDIL_VEHICLE_STATE_SHM "bobdil_state"

/* Conditioned force feedback, written by StepThread and consumed by HidThread. HidThread applies its own watchdog on top of this: a stale or non-finite command decays to zero rather than being held. */
typedef struct {
    uint64_t host_time_ns; /* [ns] Stamp used by the HidThread staleness watchdog */
    double torque_nm; /* [N.m]  */
    double spring_coeff; /* [N.m/rad] Optional centering spring for the parked state */
    double damper_coeff; /* [N.m.s/rad]  */
    uint64_t flags; /* [-] See ffb_flags enum */
} bobdil_ffb_command_t;
#define BOBDIL_FFB_COMMAND_SIZE 40
#define BOBDIL_FFB_COMMAND_SHM "bobdil_ffb"

/* One record per step, pushed by StepThread when --trace is on. The stamps bound the five phases of a step; the input fields carry which sample it consumed, so a re-used (stale) sample is visible as such rather than showing up as a suspiciously fast step. */
typedef struct {
    uint64_t step_index; /* [-] Joins to vehicle_state */
    uint64_t input_host_time_ns; /* [ns] Stamp of the sample this step consumed; start of the input-age leg */
    uint64_t input_sample_index; /* [-] Unchanged from the previous step means the loop ran on a stale input */
    uint64_t t_step_start; /* [ns]  */
    uint64_t t_after_read; /* [ns] Bounds the seqlock read */
    uint64_t t_after_shape; /* [ns] Bounds input_shaper */
    uint64_t t_after_plant; /* [ns] Bounds plant.step -- the span Phase 0 cares about */
    uint64_t t_after_ffb; /* [ns] Bounds the conditioning chain */
    uint64_t t_after_publish; /* [ns] Bounds both seqlock publishes */
} bobdil_trace_step_t;
#define BOBDIL_TRACE_STEP_SIZE 72

/* One record per HidThread iteration, pushed when --trace is on. command_host_time_ns is the StepThread publish stamp the command carried, which is what joins a delivered torque back to the step that produced it. */
typedef struct {
    uint64_t command_host_time_ns; /* [ns] Join key -- equals trace_step.t_after_publish for the producing step */
    uint64_t t_pickup; /* [ns] When HidThread read the command */
    uint64_t t_after_apply; /* [ns] When the device had been handed the torque */
    uint64_t sample_index; /* [-] The HID sample this iteration took */
    uint64_t flags; /* [-] See trace_flags enum -- a stale command is a broken leg, not a slow one */
} bobdil_trace_device_t;
#define BOBDIL_TRACE_DEVICE_SIZE 40

/* Which rung of the plant ladder produced a frame. */
#define BOBDIL_KERNEL_ID_NONE 0ULL
#define BOBDIL_KERNEL_ID_REDUCED14DOF 1ULL
#define BOBDIL_KERNEL_ID_VEHICLE_RT 2ULL
#define BOBDIL_KERNEL_ID_VEHICLE_FMI 3ULL

/* Sticky per-session faults. Any non-zero value is surfaced in the UI. */
#define BOBDIL_FAULT_FLAGS_NONE 0ULL
#define BOBDIL_FAULT_FLAGS_PLANT_NONFINITE 1ULL
#define BOBDIL_FAULT_FLAGS_DEADLINE_MISSED 2ULL
#define BOBDIL_FAULT_FLAGS_FFB_CLAMPED 4ULL
#define BOBDIL_FAULT_FLAGS_TELEMETRY_OVERFLOW 8ULL
#define BOBDIL_FAULT_FLAGS_DEVICE_LOST 16ULL
#define BOBDIL_FAULT_FLAGS_PLANT_STEP_FAILED 32ULL
#define BOBDIL_FAULT_FLAGS_INPUT_STALE 64ULL

/* State of the feedback path. */
#define BOBDIL_FFB_FLAGS_NONE 0ULL
#define BOBDIL_FFB_FLAGS_ACTIVE 1ULL
#define BOBDIL_FFB_FLAGS_RAMPING_DOWN 2ULL
#define BOBDIL_FFB_FLAGS_DISABLED 4ULL
#define BOBDIL_FFB_FLAGS_WATCHDOG_TRIPPED 8ULL

/* What the device thread did with a command. A trace tool must keep these out of its latency percentiles: a rejected or stale command is a broken leg, and averaging it into a timing number reports a safety condition as a performance one. */
#define BOBDIL_TRACE_FLAGS_NONE 0ULL
#define BOBDIL_TRACE_FLAGS_COMMAND_FRESH 1ULL
#define BOBDIL_TRACE_FLAGS_COMMAND_STALE 2ULL
#define BOBDIL_TRACE_FLAGS_COMMAND_MISSING 4ULL
#define BOBDIL_TRACE_FLAGS_APPLY_FAILED 8ULL

#endif /* BOBDIL_FRAMES_H */